### ISSUE TITLE
Incorrect cap position number in BOM

### ISSUE THREAD

**Issue by hitmanmcc** [TzorriMahm/N64_RGB_Amp#1]
In the BOM cap C31 is mentioned twice, one of those mentions should be C41.
<img width="775" alt="image" src="https://user-images.githubusercontent.com/3464842/187290451-44cec46f-92e7-4978-9341-a582f1fde531.png">
I tried to submit a PR with the update but I do not have access rights.

**Comment by TzorriMahm** [comment]
Fixed. Thank you! :)

**Comment by hitmanmcc** [comment]
My pleasure! :)
