### ISSUE TITLE
 a lot of diagonal stripes moved

### ISSUE THREAD

**Issue by Cyrus331** [TzorriMahm/N64_RGB_Amp#2]
After I installed this module, when I used GBSC to display, a lot of diagonal stripes moved. The same happened when I added a 470R resistor to C-Sync. Has anyone encountered this situation? How to solve it?

**Comment by TzorriMahm** [comment]
Frankly, I never encountered such behavior in like 30+ installs.

Some questions:
- correct revision?
- double-checked install?
  - maybe short to ground?
- cable works properly with other consoles?
- I'm not into GBS-C, but is the Resistor between sync and ground present?
- did you buy or assembled the modding board?

**Comment by Cyrus331** [comment]
Thanks for the reply. I solved the problem unintentionally. Maybe the problem really lies with GBS-C, because I saw the resolution conversion knob on GBS-C and turned it to 720P. Miraculously, the twill lines were gone.
